run:
  build-tags:
    - apt
    - brew
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - godox
    # the following are deprecated
    - golint
    - interfacer
    - maligned
    - scopelint
