run:
  build-tags:
    - apt
    - brew
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - godox
    # the following are deprecated
    - golint
    - interfacer
    - maligned
    - scopelint

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - errors.CombineErrors(
