name: Checks

on:
  pull_request:
  push:
    branches: [trunk]

jobs:
  pre-commit:
    name: Run linters with pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0"
      - name: Install checkmake
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          go install github.com/mrtazz/checkmake/cmd/checkmake@ca982aef0af387413edc4b515880bef071730dea
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4
      - uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.34.1
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3
